#!/usr/bin/env bash
#
# Capture the real state of the Home Lab server after installation.
#
# Run on: the Ubuntu server (Phase 01, Part F)
# Usage:  ./verify-install.sh [--out report.md]
#
# Why this script exists
# ----------------------
# The project rule is that documentation must describe what is actually running,
# never what was intended (see docs/standards/documentation.md). This script
# produces a Markdown report from live command output, so the repository's
# recorded state is derived from the machine rather than from memory.
#
# SECRETS: this script deliberately never prints the contents of netplan
# configuration. Those files contain the Wi-Fi passphrase in cleartext
# (see ADR-016). It reports the file's permissions instead, and warns if they
# are too open. Its output is intended to be pasted into the repository, so it
# must be safe to paste.

set -uo pipefail   # not -e: a missing optional tool must not abort the report

OUT=""
[ "${1:-}" = "--out" ] && { OUT="${2:?--out needs a filename}"; }

have() { command -v "$1" >/dev/null 2>&1; }

# Run a command, or print a clear placeholder if it is unavailable.
run() {
  local out
  if out="$("$@" 2>&1)"; then printf '%s\n' "$out"; else printf '(unavailable: %s)\n' "$*"; fi
}

section() { printf '\n## %s\n\n' "$1"; }
block()   { printf '```text\n%s\n```\n' "$1"; }

report() {

printf '# Home Lab — Server State Report\n\n'
printf -- '- **Generated:** %s\n' "$(date -Is)"
printf -- '- **Generated by:** `scripts/server/verify-install.sh`\n'

section "1. Identity and operating system"
block "$(
  printf 'Hostname     : %s\n' "$(hostname)"
  printf 'OS           : %s\n' "$(. /etc/os-release 2>/dev/null && echo "$PRETTY_NAME")"
  printf 'Kernel       : %s\n' "$(uname -sr)"
  printf 'Architecture : %s\n' "$(uname -m)"
  printf 'Uptime       : %s\n' "$(uptime -p 2>/dev/null)"
  printf 'Boot time    : %s\n' "$(uptime -s 2>/dev/null)"
)"

section "2. Hardware"
block "$(
  printf 'CPU model    : %s\n' "$(awk -F': ' '/model name/{print $2; exit}' /proc/cpuinfo)"
  printf 'CPU cores    : %s physical / %s logical\n' \
    "$(lscpu 2>/dev/null | awk -F': +' '/^Core\(s\) per socket/{print $2}')" \
    "$(nproc)"
  printf 'Memory total : %s\n' "$(free -h | awk '/^Mem:/{print $2}')"
  printf 'Swap         : %s\n' "$(free -h | awk '/^Swap:/{print $2}')"
  printf 'Swap devices : %s\n' "$(swapon --show=NAME,SIZE,TYPE --noheadings 2>/dev/null | tr '\n' ' ')"
)"

printf '\n**Memory module layout** — this closes the open Phase 00 unknown (1x8GB vs 2x4GB):\n\n'
if have dmidecode; then
  block "$(run sudo dmidecode -t memory | grep -E '^\s*(Size|Locator|Speed|Type|Manufacturer|Part Number):' | sed 's/^[[:space:]]*//')"
else
  printf '_dmidecode not installed. Install it and re-run:_ `sudo apt install -y dmidecode`\n'
fi

section "3. Storage and LVM layout"
printf 'Block devices:\n\n'
block "$(run lsblk -o NAME,SIZE,FSTYPE,TYPE,MOUNTPOINTS)"
printf '\nLVM (see ADR-015 — guided LVM, no full-disk encryption):\n\n'
block "$(
  run sudo pvs
  echo
  run sudo vgs
  echo
  run sudo lvs
)"
printf '\nFilesystem usage:\n\n'
block "$(run df -h -x tmpfs -x efivarfs -x devtmpfs)"

printf '\n**Windows removal check** — the following must be empty:\n\n'
block "$(lsblk -o NAME,FSTYPE 2>/dev/null | grep -iE 'ntfs|bitlocker' || echo '(no NTFS/BitLocker partitions found - Windows fully removed)')"

section "4. Network"
printf 'Interfaces:\n\n'
block "$(run ip -br address)"
printf '\nDefault route and DNS:\n\n'
block "$(
  run ip route show default
  echo
  run resolvectl status --no-pager
)"

printf '\nWireless link (see ADR-016 — Wi-Fi is the reference link):\n\n'
if have iw; then
  WIFI_DEV="$(iw dev 2>/dev/null | awk '/Interface/{print $2; exit}')"
  if [ -n "${WIFI_DEV:-}" ]; then
    block "$(run iw dev "$WIFI_DEV" link)"
    printf '\nPower saving (should be **off** for an always-on server):\n\n'
    block "$(run iw dev "$WIFI_DEV" get power_save)"
  else
    printf '_No wireless interface reported by iw._\n'
  fi
else
  printf '_`iw` not installed. Install it and re-run:_ `sudo apt install -y iw`\n'
fi

printf '\nnetplan configuration files — **contents deliberately not printed**, they\n'
printf 'contain the Wi-Fi passphrase in cleartext (ADR-016). Permissions only:\n\n'
block "$(run ls -l /etc/netplan/)"

# Warn loudly if any netplan file is world- or group-readable.
LOOSE="$(find /etc/netplan -maxdepth 1 -type f \( -perm -g=r -o -perm -o=r \) 2>/dev/null)"
if [ -n "$LOOSE" ]; then
  printf '\n> **SECURITY WARNING:** these netplan files are readable beyond root and\n'
  printf '> expose the Wi-Fi passphrase. Fix with `sudo chmod 600 /etc/netplan/*.yaml`:\n>\n'
  printf '> `%s`\n' "$(echo "$LOOSE" | tr '\n' ' ')"
fi

section "5. Services"
printf 'Note: modern Ubuntu uses **socket activation** for SSH. `ssh.service` showing
'
printf '`enabled=disabled` is normal and correct **provided `ssh.socket` is enabled** —
'
printf 'that is what starts sshd on demand at boot.

'
block "$(
  for unit in ssh ssh.socket wpa_supplicant systemd-networkd unattended-upgrades; do
    printf '%-24s active=%-10s enabled=%s\n' "$unit" \
      "$(systemctl is-active "$unit" 2>/dev/null)" \
      "$(systemctl is-enabled "$unit" 2>/dev/null)"
  done
)"

printf '\nAutomatic security updates:\n\n'
block "$(run systemctl list-timers --all --no-pager apt-daily-upgrade.timer)"

section "6. Security posture (Phase 01 baseline)"
printf 'SSH is installed in Phase 01 but hardened in Phase 03. Password\n'
printf 'authentication being enabled here is a **known, time-boxed risk**:\n\n'
block "$(
  run sudo sshd -T | grep -E '^(permitrootlogin|passwordauthentication|pubkeyauthentication|port) '
)"
block "$(
  printf 'Admin user   : %s\n' "$(id -un)"
  printf 'Groups       : %s\n' "$(id -Gn)"
  printf 'Reboot needed: %s\n' "$([ -f /var/run/reboot-required ] && echo YES || echo no)"
)"

section "7. Versions for docs/reference/software-stack.md"
printf '| Component | Tested version |\n|---|---|\n'
printf '| Ubuntu Server | %s |\n' "$(. /etc/os-release 2>/dev/null && echo "$VERSION")"
printf '| Kernel | %s |\n' "$(uname -r)"
printf '| OpenSSH server | %s |\n' "$(sshd -V 2>&1 | head -1 || dpkg-query -W -f='${Version}' openssh-server 2>/dev/null)"
printf '| systemd | %s |\n' "$(systemctl --version 2>/dev/null | awk 'NR==1{print $2}')"
printf '| netplan | %s |\n' "$(dpkg-query -W -f='${Version}' netplan.io 2>/dev/null)"
printf '| wpasupplicant | %s |\n' "$(dpkg-query -W -f='${Version}' wpasupplicant 2>/dev/null)"

printf '\n---\n_Paste relevant sections into `docs/reference/` and the phase handover._\n'

}

if [ -n "$OUT" ]; then
  report > "$OUT"
  echo "Report written to: $OUT"
else
  report
fi
