#!/usr/bin/env bash
#
# Verify the Home Lab remote-access posture from live output.
#
# Run on: the Ubuntu server
# Usage:  ./verify-remote-access.sh [--out report.md]
# Phase:  03 (Remote Access). See docs/handovers/03-remote-access.md.
#
# Companion to verify-install.sh, which captures the Phase 01 base system.
# This script answers one question: is remote access actually in the state the
# repository claims, right now?
#
# It deliberately checks the RUNNING SERVER rather than the configuration files.
# Phase 03 spent a wrong turn on exactly that distinction: `sshd -T` reported
# passwordauthentication no while the running daemon still accepted passwords,
# because it had parsed its configuration four hours earlier and nothing had
# told it to re-read. A file is not a control until the process holding it has
# re-read it. See the build log for the full story.
#
# SECRETS: prints no key material, no tailnet auth keys, and no netplan
# contents. Its output is meant to be pasted into the repository, so it must be
# safe to paste. The Tailscale MagicDNS suffix IS masked, because it is a
# globally unique identifier tied to the owner's account and this repository is
# intended to become public.

set -uo pipefail   # not -e: one unavailable tool must not abort the report

OUT=""
[ "${1:-}" = "--out" ] && { OUT="${2:?--out needs a filename}"; }

have() { command -v "$1" >/dev/null 2>&1; }
section() { printf '\n## %s\n\n' "$1"; }
block()   { printf '```text\n%s\n```\n' "$1"; }

# Redact the two things in Tailscale output that must never reach the
# repository: the tailnet suffix (a globally unique identifier tied to the
# owner's account) and the account identity itself, which tailscale status
# prints against every node as an email address.
mask_sensitive() {
  local suffix
  suffix="$(tailscale status --json 2>/dev/null \
            | sed -n 's/.*"MagicDNSSuffix": *"\([^"]*\)".*/\1/p' | head -1)"
  if [ -n "$suffix" ]; then
    sed "s/${suffix//./\\.}/<tailnet>.ts.net/g"
  else
    cat
  fi | sed -E 's/[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]*/<account>/g'
}

report() {

printf '# Home Lab — Remote Access Verification\n\n'
printf -- '- **Generated:** %s\n' "$(date -Is)"
printf -- '- **Generated by:** `scripts/server/verify-remote-access.sh`\n'
printf -- '- **Host:** %s\n' "$(hostname)"

# =========================================================================
section "1. What the running SSH daemon actually does"
# =========================================================================
#
# The authoritative check. We ask the server, over the network, which
# authentication methods it offers — by attempting to authenticate with none
# of them and reading the refusal. The methods it names are the ones it will
# accept.
#
#   Permission denied (publickey)           <- passwords disabled. Correct.
#   Permission denied (publickey,password)  <- passwords STILL ACCEPTED.
#
# UserKnownHostsFile=/dev/null keeps this probe from writing to known_hosts;
# StrictHostKeyChecking=no stops it prompting. Both are safe here because we
# are not trusting this connection with anything — we only read the refusal.

if have ssh; then
  ADVERTISED="$(ssh -o BatchMode=yes \
                    -o PreferredAuthentications=none \
                    -o StrictHostKeyChecking=no \
                    -o UserKnownHostsFile=/dev/null \
                    -o ConnectTimeout=10 \
                    "$(id -un)@localhost" true 2>&1 | tail -1)"
  block "$ADVERTISED"
  case "$ADVERTISED" in
    *"(publickey)"*)
      printf '\n**PASS** — the running daemon offers public key only.\n' ;;
    *password*)
      printf '\n> **FAIL: the running server still accepts passwords.**\n>\n'
      printf '> The configuration files may well be correct. The daemon has not\n'
      printf '> re-read them. Fix with:\n>\n'
      printf '>     sudo systemctl reload ssh\n' ;;
    *)
      printf '\n_Inconclusive — could not probe localhost._\n' ;;
  esac
else
  printf '_ssh client not available to probe with._\n'
fi

# =========================================================================
section "2. Is the daemon older than its configuration?"
# =========================================================================
#
# The trap that caused the above to matter. If any sshd config file has been
# modified since the daemon started, the daemon is serving something other
# than what is on disk, and sshd -T will not tell you.

# StateChangeTimestamp, NOT ActiveEnterTimestamp. A reload does not restart the
# service, so ActiveEnterTimestamp still reports the original boot and this
# check would report every correctly-reloaded daemon as stale. Reloading is the
# supported way to apply sshd configuration, so the timestamp that moves on
# reload is the one that answers the question.
DHUMAN="$(systemctl show ssh.service -p StateChangeTimestamp --value 2>/dev/null)"
[ -n "$DHUMAN" ] || DHUMAN="$(systemctl show ssh.service -p ActiveEnterTimestamp --value 2>/dev/null)"
NEWEST=""
NEWEST_T=0
for f in /etc/ssh/sshd_config /etc/ssh/sshd_config.d/*.conf; do
  [ -f "$f" ] || continue
  t="$(stat -c %Y "$f")"
  [ "$t" -gt "$NEWEST_T" ] && { NEWEST_T="$t"; NEWEST="$f"; }
done
DSTART_EPOCH="$(date -d "$DHUMAN" +%s 2>/dev/null || echo 0)"

block "$(
  printf 'ssh.service started or reloaded : %s\n' "$DHUMAN"
  printf 'newest config file              : %s\n' "$NEWEST"
  printf 'modified                        : %s\n' "$(date -d "@$NEWEST_T" 2>/dev/null)"
)"

if [ "$DSTART_EPOCH" -gt 0 ] && [ "$NEWEST_T" -gt "$DSTART_EPOCH" ]; then
  printf '\n> **WARNING: configuration is newer than the running daemon.**\n>\n'
  printf '> Run `sudo systemctl reload ssh`, then re-run this script.\n'
else
  printf '\n**PASS** — the daemon has read the configuration as it now stands.\n'
fi

# =========================================================================
section "3. Effective SSH configuration"
# =========================================================================
#
# What sshd concludes after reading every drop-in in order. Necessary but NOT
# sufficient — section 1 is the real test. Included because it shows which
# values were resolved, which is what you need when they are wrong.

if have sudo && sudo -n true 2>/dev/null; then
  block "$(sudo sshd -T 2>/dev/null | grep -E '^(port|permitrootlogin|passwordauthentication|kbdinteractiveauthentication|pubkeyauthentication|authenticationmethods) ')"
else
  printf '_Needs sudo. Re-run as:_ `sudo ./verify-remote-access.sh`\n'
fi

printf '\nDrop-ins, in the order sshd reads them. **The first value of a keyword\n'
printf 'wins**, so an earlier file overrides a later one:\n\n'
block "$(ls -l /etc/ssh/sshd_config.d/*.conf 2>/dev/null)"

# =========================================================================
section "4. Authorized keys"
# =========================================================================
#
# Key material is never printed. Type, comment, permissions and count only.

AK="$HOME/.ssh/authorized_keys"
if [ -f "$AK" ]; then
  block "$(
    printf 'directory : %s\n' "$(stat -c '%A %U:%G %n' "$HOME/.ssh")"
    printf 'file      : %s\n' "$(stat -c '%A %U:%G %n' "$AK")"
    printf 'entries   : %s\n' "$(grep -c -E '^[^#[:space:]]' "$AK")"
    printf '\nkeys (type and comment only, no key material):\n'
    awk '/^[^#[:space:]]/{print "  " $1 "  " $NF}' "$AK"
  )"
  [ "$(stat -c %a "$HOME/.ssh")" = "700" ] \
    || printf '\n> **WARNING:** `~/.ssh` should be mode 700.\n'
  [ "$(stat -c %a "$AK")" = "600" ] \
    || printf '\n> **WARNING:** `authorized_keys` should be mode 600.\n'
else
  printf '\n> **WARNING:** %s does not exist. Key login is not possible.\n' "$AK"
fi

printf '\nOwnership of files root parses — anything not root-owned is a\n'
printf 'privilege-escalation path (the Phase 01 lesson):\n\n'
block "$(
  find /etc/ssh/sshd_config.d -maxdepth 1 -type f ! -user root \
    -printf '%p  owner=%u group=%g  <-- SHOULD BE root:root\n' 2>/dev/null \
    || true
  echo '(nothing listed above means all files are root-owned)'
)"

# =========================================================================
section "5. Tailscale"
# =========================================================================

if have tailscale; then
  block "$(tailscale status 2>&1 | mask_sensitive)"
  printf '\nThis node:\n\n'
  block "$(
    tailscale status --json 2>/dev/null | python3 -c '
import sys, json
try:
    s = json.load(sys.stdin)["Self"]
except Exception:
    sys.exit("(could not parse tailscale status --json)")
print("hostname   :", s.get("HostName"))
print("dns name   :", s.get("DNSName"))
print("addresses  :", ", ".join(s.get("TailscaleIPs") or []))
exp = s.get("KeyExpiry")
print("key expiry :", exp if exp else "none (expiry disabled - see ADR-019)")
print("online     :", s.get("Online"))
' 2>&1 | mask_sensitive
  )"

  # Key expiry disabled is deliberate (ADR-019) and must stay that way: an
  # unattended headless node that drops off the tailnet needs a physical visit.
  if tailscale status --json 2>/dev/null | grep -q '"KeyExpiry"'; then
    printf '\n> **WARNING: this node has a key expiry set.**\n>\n'
    printf '> When it lapses the node silently leaves the tailnet, and with no\n'
    printf '> monitor attached that means a physical visit. ADR-019 requires it\n'
    printf '> disabled: admin console -> Machines -> homelab -> Disable key expiry.\n'
  else
    printf '\n**PASS** — no key expiry set (ADR-019).\n'
  fi
else
  printf '_Tailscale is not installed._\n'
fi

block "$(
  for unit in tailscaled ssh.socket ssh.service; do
    printf '%-14s active=%-10s enabled=%s\n' "$unit" \
      "$(systemctl is-active "$unit" 2>/dev/null)" \
      "$(systemctl is-enabled "$unit" 2>/dev/null)"
  done
)"

# =========================================================================
section "6. System health"
# =========================================================================
#
# A Definition of Done item since Phase 01, which produced a machine that
# passed every functional test while a boot unit failed.

STATE="$(systemctl is-system-running 2>/dev/null)"
block "$(
  printf 'systemctl is-system-running : %s\n' "$STATE"
  printf '\nfailed units:\n'
  systemctl --failed --no-legend 2>/dev/null | sed 's/^/  /' || true
  systemctl --failed --no-legend 2>/dev/null | grep -q . || printf '  (none)\n'
)"
[ "$STATE" = "running" ] \
  && printf '\n**PASS** — system reports running with no failed units.\n' \
  || printf '\n> **WARNING:** system state is `%s`, not `running`.\n' "$STATE"

printf '\n---\n_Paste relevant sections into `docs/` and the phase handover._\n'

}

if [ -n "$OUT" ]; then
  report > "$OUT"
  echo "Report written to: $OUT"
else
  report
fi
